name: Medusa CD Pipeline

on:
  push:
    branches: [main]

env:
  AWS_REGION: "us-east-1"
  ECR_REPO: "medusa-app"
  ECS_CLUSTER: "medusa-cluster"
  ECS_SERVICE: "medusa-service"
  DB_NAME: "medusa"
  DB_USER: "medusa_admin"

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - uses: actions/checkout@v4

    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - uses: aws-actions/amazon-ecr-login@v2
      id: ecr-login

    - name: Build and Push
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.ecr-login.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPO:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPO:$IMAGE_TAG
        echo "image_uri=$ECR_REGISTRY/$ECR_REPO:$IMAGE_TAG" >> $GITHUB_OUTPUT

    - uses: hashicorp/setup-terraform@v3

    - run: terraform init
      working-directory: ./terraform

    - run: terraform apply -auto-approve
      working-directory: ./terraform
      env:
        TF_VAR_image_uri: ${{ steps.build-image.outputs.image_uri }}
        TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}